export const dynamic = 'force-dynamic'

import { NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { getServerUser } from "@/lib/session"

export async function GET(
  request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const user = await getServerUser()
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const license = await prisma.license.findUnique({
      where: { id: params.id },
      include: {
        product: {
          select: {
            id: true,
            title: true,
            slug: true,
            version: true,
            licenseType: true,
            creator: {
              select: {
                username: true,
                displayName: true,
              },
            },
          },
        },
        order: {
          select: {
            id: true,
            createdAt: true,
            total: true,
            currency: true,
          },
        },
      },
    })

    if (!license) {
      return NextResponse.json({ error: "License not found" }, { status: 404 })
    }
    if (license.userId !== user.id) {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 })
    }

    const creatorName =
      license.product.creator.displayName || license.product.creator.username
    const lines = [
      "PawVault Product License",
      "========================",
      "",
      `License key : ${license.licenseKey}`,
      `Status      : ${license.status}`,
      `Issued      : ${license.createdAt.toISOString()}`,
      ``,
      `Product     : ${license.product.title}`,
      `Version     : ${license.product.version || "N/A"}`,
      `Creator     : ${creatorName}`,
      `License type: ${license.product.licenseType || "Standard"}`,
      ``,
      `Purchase order: ${license.order.id}`,
      `Purchased     : ${license.order.createdAt.toISOString()}`,
      `Amount        : ${license.order.currency} ${license.order.total.toFixed(2)}`,
      ``,
      "Terms",
      "-----",
      "This license grants the holder the right to use this product for personal and commercial",
      "projects. The creator and its licensors retain all ownership rights. The product is licensed,",
      "not sold. Redistribution, resale, or sharing of the product files is",
      "prohibited without explicit permission from the creator.",
      "For full terms, see https://pawvault.com/license-agreement",
      "",
      "Generated by PawVault",
    ]

    const content = lines.join("\n")
    const headers = new Headers()
    headers.set("Content-Type", "text/plain; charset=utf-8")
    headers.set(
      "Content-Disposition",
      `attachment; filename="pawvault-license-${license.licenseKey}.txt"`
    )

    return new NextResponse(content, { status: 200, headers })
  } catch (error) {
    console.error("License file download error:", error)
    return NextResponse.json(
      { error: "Something went wrong" },
      { status: 500 }
    )
  }
}
