import { NextResponse } from "next/server"

export async function GET() {
  const mockPosts = [
    {
      id: "1",
      title: "Just finished my first avatar commission!",
      content: "I'm so excited to share my first completed avatar commission. It took about 2 weeks but the client is super happy. Here's a preview of the final result...",
      type: "showcase",
      author: {
        id: "u1",
        username: "avatarartist_john",
        displayName: "John Doe",
        avatar: null,
        role: "CREATOR",
        isVerified: true,
      },
      tags: ["avatar", "commission", "vrchat", "showcase"],
      likes: 42,
      replies: 8,
      views: 1250,
      isPinned: false,
      isLocked: false,
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "2",
      title: "Question about Unity 2022 LTS compatibility",
      content: "Has anyone tested their avatars with Unity 2022.3 LTS? I'm getting some shader errors with the new graphics packages. Any workarounds?",
      type: "question",
      author: {
        id: "u2",
        username: "unitydev_sarah",
        displayName: "Sarah Chen",
        avatar: null,
        role: "DEVELOPER",
        isVerified: true,
      },
      tags: ["unity", "vrchat", "shaders", "help"],
      likes: 15,
      replies: 12,
      views: 890,
      isPinned: false,
      isLocked: false,
      createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "3",
      title: "PawVault Creator Spotlight: Weekly Featured Artists",
      content: "This week we're featuring three amazing creators who have been consistently delivering quality work. Check out their stores and show them some love!",
      type: "announcement",
      author: {
        id: "u3",
        username: "pawvault_staff",
        displayName: "PawVault Team",
        avatar: null,
        role: "ADMIN",
        isVerified: true,
      },
      tags: ["announcement", "spotlight", "creators", "featured"],
      likes: 89,
      replies: 23,
      views: 3400,
      isPinned: true,
      isLocked: false,
      createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "4",
      title: "Tips for optimizing avatar performance on Quest",
      content: "Want to make your avatars Quest-compatible? Here are my top 10 tips for reducing polygon count, optimizing materials, and keeping frame rates high...",
      type: "discussion",
      author: {
        id: "u4",
        username: "questoptimizer_mike",
        displayName: "Mike Johnson",
        avatar: null,
        role: "CREATOR",
        isVerified: false,
      },
      tags: ["quest", "optimization", "tips", "tutorial"],
      likes: 67,
      replies: 15,
      views: 2100,
      isPinned: false,
      isLocked: false,
      createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    },
  ]

  return NextResponse.json({ posts: mockPosts })
}